[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Automat z.s."]
license = "LGPL-3.0-or-later"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
django-import-export-celery = {path = "../", develop = true}
django = "^5.2"
celery = "*"
redis = "*"
pyyaml = ">=6.0"

[tool.poetry.group.dev.dependencies]
black = "^26.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
