# Generated by Django 5.2.12 on 2026-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winner",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
