# Generated by Django 5.2.12 on 2026-03-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_export_celery", "0011_alter_exportjob_email_on_completion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
